#! /bin/sh

. ~/.config/bspwm/scripts/colors.sh

#~/.config/bspwm/scripts/multi_monitors.sh
polybar --reload example &
dunst &
sxhkd &
compton -bc --config ~/.config/compton/compton.conf
feh --bg-scale ~/Pictures/Wallpapers/Dreamy-Sword-Girl.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

# Widths and stuff
bspc config border_width         2
bspc config window_gap          15
# top padding is set automatically according to window_gap and size of polybar
bspc config top_padding		65

bspc config focus_follows_pointer true

# Colors
bspc config focused_border_color "$BORDER"
bspc config normal_border_color  "$BORDERNORM"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Gimp" desktop='^8' state=floating follow=on
bspc rule -a "Chromium" desktop='^2'
bspc rule -a "VirtualBox" desktop='^6' state=floating
bspc rule -a "virtualBox Machine" desktop='^7' state=floating
bspc rule -a "Emacs" state=tiled
bspc rule -a "mpv" state=floating
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
