#! /bin/sh

feh --bg-scale ~/Pictures/Wallpapers/abstract-hexagon-teal.jpg
sxhkd &
compton -bc --config ~/.config/compton/compton.conf

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          35
bspc config top_padding		50

# Colors
bspc config focused_border_color "#ccffff"
bspc config normal_border_color  "#aaeecc"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
